version: "3"
services:

  backend:
    container_name: backend
    image: vanhauknc/nodesample
    ports:
      - "8080:8080"
    networks:
      - goals-net
    restart: always


networks:
  goals-net:


